### ISSUE TITLE
Donnie Berkholz Presenting

### ISSUE THREAD

**Issue by thingles** [thingles/aws_mn#19]
@dberkholz presenting, topic not known. For #18.

**Comment by bridgetkromhout** [comment]
Hey, @dberkholz - I'm going to press the button to send the mail about http://www.meetup.com/Twin-Cities-Amazon-Web-Services-User-Group/events/202589772/ later today. Please let me know if you have more specifics in terms of title or content than _Donnie talking about AWS and "cloud"_. Thanks!

**Comment by adomeier** [comment]
FYI - Everything looks to be set for tonight.   I sent out a note to make sure folks noticed it's moved to the new 5th floor space.

CC - @bridgetkromhout @thingles @amyjpatton @ktangen

**Comment by bridgetkromhout** [comment]
Thanks, @adomeier!
