### ISSUE TITLE
Talk Idea: Hacking AWS OpsWorks

### ISSUE THREAD

**Issue by anfleene** [thingles/aws_mn#24]
At Sport Ngin we use AWS OpsWorks heavily. We running 25 applications across our platform, 50 different OpsWorks stacks between our staging and production accounts. We've been using Opsworks basically since it was announced 2 years ago. We built a command line utility([opsicle](https://github.com/sportngin/opsicle)) to help us along the way. I could give a presentation about OpsWorks in general and the evolution of how we've use it. If there's time start talking about the tradeoffs of using OpsWorks vs rolling your own chef server/provisioning setup.

**Comment by bridgetkromhout** [comment]
Hi, @anfleene  -

I'd like to announce your talk. Can you take a look at http://www.meetup.com/Twin-Cities-Amazon-Web-Services-User-Group/events/220038369/ and see how that looks? Thanks!

**Comment by anfleene** [comment]
that looks great!

**Comment by bridgetkromhout** [comment]
Great! I've announced it.

**Comment by adomeier** [comment]
@anfleene I'm sad to be missing this one!

**Comment by bridgetkromhout** [comment]
Looking forward to the meetup this week, @anfleene! :)

**Comment by thingles** [comment]
Nicely done!
