### ISSUE TITLE
Planning for Feb 18 2015 Meetup

### ISSUE THREAD

**Issue by thingles** [thingles/aws_mn#26]
- [x] Confirm speaker
- [x] Update Meetup with confirmed presenter
- [x] Building access
- [x] Food
- [x] Beverages

**Comment by adomeier** [comment]
Hey @amyjpatton @bridgetkromhout @thingles I'm going to be out with our new born so I will need others to help organize location logistics for this meet up.

**Comment by bridgetkromhout** [comment]
Hey, @amyjpatton and @thingles - who on the SPS side is handling food ordering and signage (and whatever needs to happen with security)? Thanks.

**Comment by amyjpatton** [comment]
I can take care of it. For the most part, it is all handled by our Corporate Services team anyway. 

--Amy

**Comment by bridgetkromhout** [comment]
Thanks, Amy! I added you to http://www.meetup.com/Twin-Cities-Amazon-Web-Services-User-Group/events/220038369/ as an event host, so you should be able to get the attendee list as needed.

**Comment by amyjpatton** [comment]
Great - thanks!

**Comment by thingles** [comment]
Done!
