### ISSUE TITLE
Planning for Mar 18 2015 Meetup

### ISSUE THREAD

**Issue by thingles** [thingles/aws_mn#27]
- [ ] Confirm speaker
- [ ] Update Meetup with confirmed presenter
- [ ] Building access
- [ ] Food
- [ ] Beverages

**Comment by adomeier** [comment]
I just got pinged by some folks from AWS that will be in town on March 24th for AWSome Day (http://aws.amazon.com/events/awsome-day/minneapolis/)  They said if we're having a meetup this week they would be interested in participating. 

thoughts on pushing back the meetup back a week to have them present on a topic on the 25th if they are able to stay in town?

Ping @thingles @bridgetkromhout @amyjpatton @ktangen

**Comment by bridgetkromhout** [comment]
> thoughts on pushing back the meetup back a week

I've been swamped, sorry, but I talked to @mfdii who was recently in town presenting at Target's internal devops event, and he'll be back in Minneapolis the evening of March 18th. I'm interested in having him present on some of the cloud config management topics he presented about for Chef at AWS re:invent, and he's willing to (or something along those lines).

We could round out the evening with the proposed talk on dealing with failure. I'd be in favor of keeping to our regular day with this plan, and that way, we promote the AWSome day ahead of it happening, and give the new local rep a chance to talk to people before the event itself? 

(Also I come back from bike camping late the evening of the 23th and have a lot of stuff crammed into that week already, but that's neither here nor there.)

cc @adomeier @thingles @bridgetkromhout @amyjpatton @ktangen

**Comment by bridgetkromhout** [comment]
I talked to @adomeier and he says @mfdii  on the 18th works. I'm going to ship it. The "failure" talk will work for April along with whatever else.

**Comment by bridgetkromhout** [comment]
Just waiting for something more specific than "Michael Ducy, a Global Evangelist for Chef and co-host of the podcast The Goat Farm, will talk about cloud configuration management."

**Comment by bridgetkromhout** [comment]
Announced: http://www.meetup.com/Twin-Cities-Amazon-Web-Services-User-Group/events/220920660/
