### ISSUE TITLE
Planning for Apr 15 2015 Meetup

### ISSUE THREAD

**Issue by thingles** [thingles/aws_mn#28]
- [ ] Confirm speaker
- [ ] Update Meetup with confirmed presenter
- [ ] Building access
- [ ] Food
- [ ] Beverages

**Comment by bridgetkromhout** [comment]
I'm going to be in Philly during this meetup, so I won't be present.

**Comment by thingles** [comment]
> @bridgetkromhout I won't be present

You will be missed!

**Comment by bridgetkromhout** [comment]
Slating https://github.com/thingles/aws_mn/issues/37 as possible for April if that works for everyone.

**Comment by bridgetkromhout** [comment]
> You will be missed!

Thanks. :)

**Comment by bridgetkromhout** [comment]
We have one tech-relevant but non-AWS talk now for April. He's given it at meetups before in conjunction with another talk. We could have the new local AWS rep or someone from SPS present, perhaps?

**Comment by adomeier** [comment]
@thingles @bridgetkromhout sounds like we're all out of town next week.  with out anything in the books yet should we just cancel April's Meetup?

**Comment by thingles** [comment]
I’m in Kyiv so won't be of any help (no jokes about how little help I am otherwise). I’m totally fine canceling this month.

**Comment by bridgetkromhout** [comment]
Hi, @adomeier - we have this: https://github.com/thingles/aws_mn/issues/37#issuecomment-77504490 but if none of the organizers can be there then yes, we should cancel. I'll let him know.

**Comment by bridgetkromhout** [comment]
We never scheduled one, so I just announced that it's not happening.

**Comment by adomeier** [comment]
wait... so we're closing this with out a poke at @thingles impact when he's unavailable? :)

**Comment by bridgetkromhout** [comment]
> wait... so we're closing this with out a poke at @thingles impact when he's unavailable?

@adomeier, hah! I am busy enough that his line didn't really register.

> no jokes about how little help I am otherwise

@thingles, everyone is happier when you're at the meetup. Maybe we need to measure that and graph it. :)

**Comment by adomeier** [comment]
LOL... @bridgetkromhout that last comment about graphing it.. is my favorite thing of the day today :)

**Comment by thingles** [comment]
@bridgetkromhout @adomeier you two may know better my obsession with graphing things than most people do. :-)
