### ISSUE TITLE
Planning for May 20 2015 Meetup

### ISSUE THREAD

**Issue by thingles** [thingles/aws_mn#29]
- [ ] Confirm speaker
- [ ] Update Meetup with confirmed presenter
- [ ] Building access
- [ ] Food
- [ ] Beverages

**Comment by bridgetkromhout** [comment]
Hey, @thingles, @adomeier - I've been out of the loop, but did we have a speaker in mind for this? Thanks.

**Comment by adomeier** [comment]
Hey @bridgetkromhout I don't have anything in the works but I can start digging around for something.  I should finally be around for the meetup!

**Comment by bridgetkromhout** [comment]
Hey, @adomeier - I reached out to Jeremy because I know he had an idea a while ago (haven't heard back), but I think it would be great to get someone or a few someones from SPS to talk about all the cool stuff you folks are doing.

**Comment by adomeier** [comment]
ok @bridgetkromhout , if we want an sps-er I can poke around a bunch here.  I will start on that today.

**Comment by bridgetkromhout** [comment]
@adomeier SPS has been gracious as hosts, and I think everyone who visits and sees your great space would also like to know what's happening in your AWS adventures! :)

**Comment by adomeier** [comment]
@bridgetkromhout we're just solving world peace and world hunger one supply chain doc at a time.  nothing too exciting! ;)

**Comment by thingles** [comment]
FYI, I’m going to be in Australia all next week. Yeah for jet lag. :-\ Will not be around next week.

**Comment by bridgetkromhout** [comment]
Have fun in Oz!

**Comment by bridgetkromhout** [comment]
@adomeier, any leads on a speaker? If you don't have something lined up yet, I'm inclined to just tell people to go to this: http://www.meetup.com/Skyway-Software-Symposium/events/222503626/

**Comment by adomeier** [comment]
@bridgetkromhout oh bummer, same day even.  I think from past Meetups when they are on the same week that was hard enough on attendance.  I don't have anything really solid right now, just some warm interest.  let's tell everyone to go to that this time around.

**Comment by bridgetkromhout** [comment]
Okay, done.
