### ISSUE TITLE
Planning for Jun 17 2015 Meetup

### ISSUE THREAD

**Issue by thingles** [thingles/aws_mn#30]
- [ ] Confirm speaker
- [ ] Update Meetup with confirmed presenter
- [ ] Building access
- [ ] Food
- [ ] Beverages

**Comment by bridgetkromhout** [comment]
I am going to be flying back from Monitorama in Portland that night, touching down at MSP at 9:05pm. So I won't make it to the meetup. Let's start planning now so we can get the speaker set up. @adomeier, can you get someone from SPS?

**Comment by adomeier** [comment]
The net has been casted... I will keep you posted.  In a week or two I will start fishing externally if I don't get any takers ( @bridgetkromhout )

**Comment by adomeier** [comment]
Hey @bridgetkromhout and @thingles from chatting with folks between summer vacations, work, and lame excuses I have been unable to land a speaker for this meetup and now my availability is also in question.  I really hate skipping this for another month but I think we may need to?... Thoughts?

**Comment by bridgetkromhout** [comment]
I have no ability to speak, attend, or wrangle speakers for this meetup on the 17th of June. I'm in Philly today and New York tomorrow and Portland next week. If we need to not have one I think that's okay. It's summertime.

**Comment by adomeier** [comment]
@bridgetkromhout I knew you were on the crazy train, but didn't realize it was that crazy!  hopefully it's fun/going ok!  Enjoy Monitorama, wish I could be there with ya!!!

**Comment by thingles** [comment]
Seems like we have at least an implicit decision to cancel.. Is that the plan? I don't think we've communicated anything yet.

I would like to get a small group of @bridgetkromhout @adomeier and maybe a couple of others together to discuss the meetup, plans and what we are trying to achieve. I think it would be good to just discuss through some things so we can clarify our meetings more. Agree?

**Comment by bridgetkromhout** [comment]
> Seems like we have at least an implicit decision to cancel.. Is that the plan? I don't think we've communicated anything yet.

I don't think we need to communicate anything unless we want to send the members to another meetup that night. We didn't have one scheduled as a published "upcoming" event, so there is nothing to cancel.

> I would like to get a small group of @bridgetkromhout @adomeier and maybe a couple of others together to discuss the meetup

Sure, sounds great. If you'd like this to be before devopsdays Minneapolis, please send a doodle with your suggested dates/times and I'll see what I can do.
