### ISSUE TITLE
Planning for Aug 19 2015 Meetup

### ISSUE THREAD

**Issue by thingles** [thingles/aws_mn#32]
- [ ] Confirm speaker
- [ ] Update Meetup with confirmed presenter
- [ ] Building access
- [ ] Food
- [ ] Beverages

**Comment by adomeier** [comment]
@bridgetkromhout @thingles I think I can finally be around to help organize this one.  Anyone else in?  Anyone have talks in mind that you might have in the hopper otherwise I will start poking.

**Comment by adomeier** [comment]
@thingles @bridgetkromhout I have been striking out on presenters.  Any thoughts?  Probably need to cancel or book it today.

**Comment by bridgetkromhout** [comment]
> @thingles @bridgetkromhout I have been striking out on presenters. Any thoughts? Probably need to cancel or book it today.

I don't think we should try to have one this month.

**Comment by bridgetkromhout** [comment]
I'm just going to close this one out.
